### ISSUE TITLE
Encourage bios to be written in 3rd person.

### ISSUE THREAD

**Issue by ann-kilzer** [WWCodeTokyo/speak-her-db#119]
**Is your feature request related to a problem? Please describe.**
I notice a lot of the bios are written in the 1st person (I ...). Let's encourage users to submit them in the third person (she/they)

**Describe the solution you'd like**
- [ ] Change the hint on the speaker bio box to a `persistent-hint`.
- [ ] Review the bios in Airtable and rewrite them in 3rd person.

**Describe alternatives you've considered**
- [ ] Could also write a vuelidate custom validator to check for use of "I" or わたし.

**Additional context**

Please solve each of these as separate PRs / tasks.

**Comment by tuttiq** [comment]
In hindsight, our site is not a conference CFP form, it's just a database of profiles, so I don't see why bios in first person are a big problem (people write their LinkedIn bios in first person and it seems acceptable?).

If we put too many small restrictions, it just makes the form harder to fill and doesn't bring much value (I don't think bios in first person are a huge decrease in the quality of entries...). We're just adding the risk of more people dropping the nomination process halfway through because it's too "mendokusai".

Honestly, if everyone is okay and no feelings are harmed, I'd vote to just drop this feature and keep the form simple.

I would even go further and open a ticket to *remove* the "mandatory" condition from the "Japanese name" as well, since some foreigners may prefer to not have their names translated (or just don't know how to translate it / how to input Japanese characters).

What do you think?

**Comment by RossellaFer** [comment]
I agree with this, since it generates an error maybe it would discourage people from completing the form. 
However, the persistent hint is a good idea, but this is only a guideline instead of validation. It's a minor change but I will make another PR for this

**Comment by ann-kilzer** [comment]
Yeah, perhaps we are making another challenging form to complete. 😩 

Thanks @RossellaFer for your hard work on this ticket nonetheless.

**Comment by tuttiq** [comment]
Thank you both for your work on this! ❤️
