### ISSUE TITLE
Make a QA Airtable

### ISSUE THREAD

**Issue by ann-kilzer** [WWCodeTokyo/speak-her-db#137]
Make another Airtable with dummy data

**Comment by tuttiq** [comment]
I created a Dev DB on Airtable with dummy fake data so we can use this one on Development stage. Since it's all dummy data, I generated this link that anyone with the link can access the DB with read-only access: https://airtable.com/shrnNqPNgoe0R5fJo

I'll work on a PR to automatically select the Dev or Prod DB depending on the app environment setting, and I'll add the info on README as well. Let me know if you have any concerns as of now.
